

require "modules.quick-select"
require "modules.clipboard"
require "modules.stack-undo"
require "modules.terminal"
require "modules.auto-complete"
require "modules.auto-pair"
require "modules.comments"
require "modules.switch"
require "modules.run-code"
require "modules.auto-align"
require "modules.quote-match"
require "modules.surround"
require "modules.fzf"
